VPATH += :$(HALPATH)/xmega
SRC += uart.c usart_driver.c xmega_hal.c
EXTRAINCDIRS += $(HALPATH)/xmega

MCU_FLAGS = -mmcu=$(MCU)
CFLAGS += -fpack-struct

CC = avr-gcc
OBJCOPY = avr-objcopy
OBJDUMP = avr-objdump
STRIP = avr-strip
SIZE = avr-size
AR = avr-ar rcs
NM = avr-nm