os: linux
language: python
dist: xenial
python: "3.8"

addons:
  apt:
    packages:
      - swig
      - gcc

install:
  - pip install codecov
  - mkdir pyecsca/codegen/tommath
  - cd ext/
  - make host
  - cp libtommath/tommath.h ../pyecsca/codegen/tommath/tommath.h
  - git clone https://github.com/J08nY/pyecsca
  - cd pyecsca/
  - git submodule update --init --recursive
  - pip install -e ".[chipwhisperer]"
  - cd ../..
  - pip install -e ".[test, dev]"

script:
  - make -i typecheck
  - make -i codestyle
  - make test

after_success:
  - codecov
