os: linux
language: python
dist: focal
python:
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - swig
      - gcc
      - llvm-10
      - libllvm10
      - llvm-10-dev

env:
  - LLVM_CONFIG=/usr/bin/llvm-config-10

install:
  - pip install codecov
  - cd ext/
  - make host
  - git clone https://github.com/J08nY/pyecsca
  - cd pyecsca/
  - git submodule update --init --recursive
  - pip install -e ".[chipwhisperer]"
  - cd ../..
  - pip install -e ".[test, dev]"

script:
  - make -i typecheck
  - make -i codestyle
  - make test

after_success:
  - codecov
